stolostron/search-collector

build/Configfile
**Related Issue:**  N/A
- Update contact info (remove personal information)
=> Update contact information

CONTRIBUTING.md, Makefile
**Related Issue:**  open-cluster-management/backlog#9582
=> Add CONTRIBUTING.md

go.mod, go.sum
**Related Issue:**  open-cluster-management/backlog#9833
Update version to 0.3.5
=> [release 2.1] update golang.org/x/text version

test-data/daemonset.json, test-data/deployment.json, test-data/replicaset.json
**Related Issue:**  open-cluster-management/backlog#10696
=> update apiVersion of test data

go.mod, go.sum
**Related Issue:**  open-cluster-management/backlog#9599
=> update deislabs/oras to latest version

pkg/transforms/policyreport.go, test-data/policyreport.json
=>  migrated to v1alpha2

pkg/transforms/policyreport.go, pkg/transforms/policyreport_test.go, test-data/policyreport.json
**Related Issue:**  open-cluster-management/backlog#11701
Make changes to consolidate all policies in one report
=> loop through and get all policies in the report

pkg/transforms/pod.go, pkg/transforms/pod_test.go
Signed-off-by: Richie Piya <rpiyasirisilp@gmail.com>
**Related Issue:**  https://github.com/open-cluster-management/backlog/issues/9000
**Description of changes**
- get owner name and kind for pod resources
=> add ownerName and ownerKind to node props

pkg/transforms/argoapplication.go, pkg/transforms/argoapplication_test.go, test-data/argoapplication.json
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
**Related Issue:**  open-cluster-management/backlog#11584
Indexes ApplicationSet name from the ownerReferences for Argo applications.
=> Index ApplicationSet owner for Argo apps

pkg/transforms/policyreport.go, pkg/transforms/policyreport_test.go
**Related Issue:**  open-cluster-management/backlog#12304
- added insight severity counts.
=> Add pr severity

pkg/transforms/policyreport.go, pkg/transforms/policyreport_test.go
Change the following names:
- numInsightPolicies -> numPolicyViolations
- insightPolicies -> policyViolations
=> Change field names for policyreport

main.go, readme.md
**Related Issue:**  open-cluster-management/backlog#12714
Add instructions on new PROW based contribution flow. Fork/merge instead of branch/merge
=> Add contribution instructions to search-collector README.

.travis.yml
**Related Issue:**  open-cluster-management/backlog#10511
- remove sonar and fast-forward
=> Remove Sonar and Fast Forward

.travis.yml
**Related Issue:**  open-cluster-management/backlog#10511
- Remove publish job for prow migration
=> Remove publish

readme.md
**Related Issue:**  open-cluster-management/backlog#14456
- Update docker image
=> [2.3] Rebuild to update base image

readme.md
**Related Issue:**  open-cluster-management/backlog#14456
- Update docker image
=> [2.3] Rebuild to update image

Dockerfile, readme.md
**Related Issue:**  open-cluster-management/backlog#14456
- Update UBI image to ubi-minimal:8.4 to resolve vulnerabilities.
=> [2.3] Use ubi-minimal:8.4

readme.md
Testing to see if fast-forward works on prow for search-collector
=> Testing Fast Forward

.travis.yml
**Related Issue:**  open-cluster-management/backlog#10511
- Disable travis jobs for main and release-2.4 branches.  Moving to prow.
=> Disable travis jobs

readme.md
Signed-off-by: mqhackett <mahacket@redhat.com>
**Related Issue:**  open-cluster-management/backlog#10511
- Rebuild project to test e2e test
- add DCO sign-off to most recent commit
=> Rebuild project to test e2e test with DCO signoff

readme.md
Signed-off-by: dislbenn <lavontae.bennett@gmail.com>
=> Re-trigger sonar-scan

readme.md
Signed-off-by: mqhackett <mahacket@redhat.com>
**Related Issue:**  open-cluster-management/backlog#17755
No-op PR to verify fast-forward to release-2.5 branch works.
=> no-op change rebuild date to verify-ff

main.go, pkg/config/config.go, pkg/config/kubeClient.go, pkg/lease/lease.go, pkg/lease/lease_test.go, pkg/send/sender.go
**Related Issue:**  open-cluster-management/backlog#17342
open-cluster-management/backlog#17789
=> [release 2.4] Use the most current kube client connection for lease

pkg/send/sender.go
Signed-off-by: xavier dharmaiyan <xavier@redhat.com>
=>  when resetting config  send full load

pkg/send/sender.go
Signed-off-by: xavier dharmaiyan <xavier@redhat.com>
=> send full load when on error

.travis.yml, Dockerfile, Makefile.prow, go.mod
**Related Issue:**  open-cluster-management/backlog#15572
=> [release 2.3] update 2.3 to go 1.17

pkg/send/sender.go
**Related Issue:**  open-cluster-management/backlog#19855
=> update sender vars when reloading config

pkg/send/sender.go
**Related Issue:**  https://github.com/stolostron/backlog/issues/19855
Port https://github.com/stolostron/search-collector/pull/188/files to 2.4.3
=> [release 2.4] Update sender vars when reloading config

OWNERS
Signed-off-by: Jorge Padilla <jpadilla@redhat.com>
**Related Issue:**  open-cluster-management/backlog#20225
- Prow build for PR #191 failed, triggering new build.
=> Trigger prow build

readme.md
**Related Issue:**  open-cluster-management/backlog#20225 for Dev Preview - Search Configurable Collections
Dev writeup for how to use control resources.
=> Instructions for allow/deny list

pkg/transforms/policyreport.go, test-data/policyreport.json
Filter grc sourced violations from PolicyReport search responses.
=> [2.4] Filter grc source violations from policyreport

readme.md
**Related Issue:**  open-cluster-management/backlog#22038
No-op PR for search-collector package vulnerability bug
=> No-op PR for search-collector package vulnerability bug

pkg/informer/supportedResources.go
**Related Issue:** No issue related
minor comment correction within `supportedResouces.go`
=> minor comment edit GET -> WATCH

Makefile, main.go, pkg/config/config.go, pkg/informer/informer.go, pkg/informer/informer_test.go, pkg/informer/sample-allow.yaml, pkg/informer/sample-allowdeny.yaml, pkg/informer/sample-deny.yaml, pkg/informer/sample-samerec.yaml, pkg/informer/supportedResources.go, pkg/informer/supportedResources_test.go, readme.md
**Related Issue:**  open-cluster-management/backlog#20225
Adding this feature for search-collector 2.4
As an ACM user, I want to control the resources collected by search from my managed clusters
=> [Release-2.4] allow/deny resources feature for 2.4

go.mod, go.sum
**Related Issue:**  open-cluster-management/backlog#20213
=> [release 2.4] update deps for crypto

readme.md
Related issue: https://github.com/stolostron/backlog/issues/23618
Signed-off-by: dislbenn <dbennett@redhat.com>
**Related Issue:**  stolostron/backlog#<ISSUE_NUMBER>
=> Imagescan Rebuild: 2022-07-05

pkg/transforms/transformer.go, pkg/transforms/transformer_test.go
Signed-off-by: Xavier Dharmaiyan <xavier@redhat.com>
**Related Issue:**  stolostron/backlog#<ISSUE_NUMBER>
=> added kind plural to properties

Dockerfile, go.mod
**Related Issue:**  stolostron/backlog#24212
=> [2.5 new] update go to 1.18 for 2.5

Dockerfile, go.mod
**Related Issue:**  stolostron/backlog#24212
=> [2.4] update go to 1.18

pkg/informer/supportedResources.go
**Related Issue:**  stolostron/backlog#25398
=> Apigroupversion to get all apigroups

pkg/informer/supportedResources.go
**Related Issue:**  stolostron/backlog#25398
- Correct apigroup used to match the allow/deny list.
=> [2.5] Apigroupversion to get all apigroups

pkg/informer/supportedResources.go
**Related Issue:**  stolostron/backlog#25398
=> [2.4] Apigroupversion to get all apigroups

readme.md
Issue: https://github.com/stolostron/backlog/issues/25040
PR created using automation.
=> [release-2.6] Trigger prow rebuild 2022-09-09

README.md
**Related Issue:**  https://github.com/stolostron/backlog/issues/25040
- Update and rename readme.md to README.md
=> Trigger prow rebuild

pkg/transforms/argoapplication.go, pkg/transforms/argoapplication_test.go, test-data/argoapplication.json
Signed-off-by: Xiangjing Li <xiangli@redhat.com>
https://issues.redhat.com/browse/ACM-1702
enhance search collectors to be able to collect resource list and error/warning conditions from the argocd application status
=> Collect resources and conditions from ArgoCD application status

pkg/transforms/argoapplication.go, pkg/transforms/argoapplication_test.go, test-data/argoapplication.json
Signed-off-by: Xiangjing Li <xiangli@redhat.com>
append the error message is in operationState.message to the error condition property
=> append operator error message to property

.github/pull_request_template.md, pkg/config/config.go
**Related Issue:**  N/A
- Update PR template
- Update version
=> Update PR template

pkg/send/sender_test.go
N/A
- Fix test failing intermittently.
=> Fix test failing intermittently

Dockerfile, Makefile, Makefile.prow, go.mod, pkg/reconciler/reconciler_test.go, pkg/send/httpsClient.go, pkg/transforms/testutils.go
https://issues.redhat.com/browse/ACM-5513
- Update go to v1.20
=> [release-2.7] ACM-5513: Update go to v1.20

Makefile, Makefile.prow, pkg/reconciler/reconciler_test.go, pkg/send/httpsClient.go, pkg/send/sender.go, pkg/transforms/testutils.go
https://issues.redhat.com/browse/ACM-5698
- Fixes regression in retry logic introduced by PR #242
=> ACM-5698 Fix regression on retry logic

Dockerfile, Makefile, Makefile.prow, go.mod, pkg/reconciler/reconciler_test.go, pkg/send/httpsClient.go, pkg/transforms/testutils.go
https://issues.redhat.com/browse/ACM-5513
- Update go to version 1.20
=> [release-2.6] ACM-5513: Update go to v1.20

pkg/transforms/argoapplication.go, pkg/transforms/argoapplication_test.go, test-data/argoapplication.json
https://issues.redhat.com/browse/ACM-6165
- ArgoCD resources that failed to deploy are not included in the related resources. These resources are included to a new _missingResources property.
=> ACM-6165 Implement feature to add missing argocd resources

pkg/transforms/transformer.go
=> Reduce code duplication

pkg/transforms/node.go, pkg/transforms/node_test.go, test-data/node.json
N/A
- Added the Node `status` field.
=> Collect node status field

pkg/transforms/genericresource.go
N/A
- Reduced log level when jsonpath can't find field.
=> Reduce logs from configurable transform

pkg/reconciler/reconciler_test.go, pkg/transforms/genericResourceConfig.go, pkg/transforms/genericResource_test.go, test-data/virtualmachine.json
ACM-10917 - extract data from virtualmachines
https://issues.redhat.com/browse/ACM-10917
- Added ...
=> ACM-10917 - extract data from virtualmachines

pkg/config/config.go, pkg/transforms/common.go, pkg/transforms/common_test.go, pkg/transforms/genericResource_test.go, pkg/transforms/genericresource.go, test-data/clusterserviceversion.json
Relates:
https://issues.redhat.com/browse/ACM-13031
=> Add annotations to the index

pkg/reconciler/reconciler_test.go, pkg/transforms/genericResourceConfig.go, pkg/transforms/genericResource_test.go, test-data/virtualmachineinstance.json
- Added VirtualMachineInstace definition 
- custom properties Node & IP address
=> Add VirtualMachineInstance definition

Dockerfile, vbh/build-harness/Dockerfile
N/A
- Restore updates pushed by konflux with PR #305 and #306
=> Restore updates from konflux

pkg/transforms/transformer.go, pkg/transforms/vapbinding.go, pkg/transforms/vapbinding_test.go, test-data/vapbinding.json
Ref: https://issues.redhat.com/browse/ACM-14837
[](https://issues.redhat.com/browse/ACM-14837)
https://issues.redhat.com/browse/ACM-14837
- Added ValidatingAdmissionPolicyBinding resource
=> Add ValidatingAdmissionPolicyBinding resource

renovate.json
- Update konflux runtime to first day of the month for less  konflux pr toil.
=> update konflux run time to once monthly

pkg/transforms/policyreport.go, pkg/transforms/policyreport_test.go
https://issues.redhat.com/browse/ACM-16775
Add the 'rules' property to thePolicyReport result
- change 'ruleNames' to 'rules'
=> ACM-16775: Add the 'rules' property to thePolicyReport result

pkg/transforms/common.go, pkg/transforms/common_test.go, pkg/transforms/genericresource.go
https://issues.redhat.com/browse/ACM-16115](https://issues.redhat.com/browse/ACM-16115)
- Add gatekeeper mutation edges
=> Add gatekeeper mutation edges

.tekton/search-collector-acm-213-pull-request.yaml, .tekton/search-collector-acm-213-push.yaml, Dockerfile
n/a
- Merge konflux commits to main.
=> Merge konflux updates for release-2.13 to main

pkg/transforms/kyverno.go, pkg/transforms/kyverno_test.go
Ref: https://issues.redhat.com/browse/ACM-17882
Since Kyverno validationFailureAction deprecation now, some users use failureAction in rule as well. We need to prioritize validationFailureAction and failureAction. 
From Kyverno doc: ref: https://kyverno.io/docs/writing-policies/policy-settings/
validationFailureAction: controls if a validation policy rule failure should block the admission review request (Enforce) or allow (Audit) the admission review request and report the policy failure in a policy report. Defaults to Audit. This field is deprecated as of 1.13. Scheduled to be removed in a future version. Use failureAction under the validate rule instead.
=> Fix Kyverno validationFailureAction deprecation issue

README.md
- no-op pipeline fix for https://redhat-internal.slack.com/archives/C04L50S5XM4/p1740673675076869
=> fix z stream bvt with no-op

pkg/transforms/genericResourceConfig.go, pkg/transforms/genericResource_test.go
https://issues.redhat.com/browse/ACM-18151
- Added more vm properties including agentConnected status, flavor, osVersion, osName, workload type, vmSize
=> ACM-18151: index more vm properties

.ci-operator.yaml
https://issues.redhat.com/browse/ACM-18716
- Local ci config to simplify go version updates
Note, this needs an update in prow before it takes effect.
=> ACM-18716 Add local CI config

.tekton/search-collector-acm-210-pull-request.yaml, .tekton/search-collector-acm-210-push.yaml
**Related Issue:**  https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.3/MIGRATION.md
- Update konflux config
=> [release-2.10] Update Konflux config

.ci-operator.yaml, Dockerfile, Dockerfile.rhtap, go.mod
https://issues.redhat.com/browse/ACM-18716
- Go 1.23
- UBI 9
=> ACM-18716 Update to go1.23 and UBI 9

go.mod, go.sum
https://www.cve.org/CVERecord?id=CVE-2025-22868
https://www.cve.org/CVERecord?id=CVE-2025-22869
Updated affected libraries
=> CVE-2025-22868/22869

.ci-operator.yaml, Dockerfile, Dockerfile.rhtap, go.mod
manual cherry-pick of https://github.com/stolostron/search-collector/pull/438
=> release 2.12 ACM-18716 Update to go1.23 and UBI 9 (#438)

.ci-operator.yaml, Dockerfile, Dockerfile.rhtap, Makefile, Makefile.prow, go.mod
- Update to Go 1.23 and add .ci-operator.yaml like https://github.com/stolostron/search-collector/pull/485
=> [release-2.10] update go 1.23

.ci-operator.yaml, Dockerfile, Makefile, Makefile.prow, go.mod
- Added .ci-operator.yaml file and updated go to 1.23
=> [release 2.9] go 1.23 update

pkg/reconciler/reconciler_test.go, pkg/transforms/genericResourceConfig.go, pkg/transforms/genericResource_test.go, test-data/storageclass.json
https://issues.redhat.com/browse/ACM-18089
- Added provisioner field of kind StorageClass to be indexed by Search.
=> ACM-18089 index provisioner field for kind storageclass

.tekton/search-collector-acm-214-pull-request.yaml, .tekton/search-collector-acm-214-push.yaml, Dockerfile, Dockerfile.rhtap, renovate.json
N/A
- [Enabling hermetic builds in Konflux](https://konflux.pages.redhat.com/docs/users/building/hermetic-builds.html)
- [Prefetching package manager dependencies for hermetic builds](https://konflux.pages.redhat.com/docs/users/building/prefetching-dependencies.html)
- Updates renovate.json
=> Enable Konflux hermetic builds

pkg/reconciler/reconciler.go
=> [release-2.13] ACM-17312 Reduce CPU by skipping edge rebuild when nothing has changed

pkg/send/sender.go
https://issues.redhat.com/browse/ACM-16129
- Added X-Clear-All header to request to indexer. Depends on https://github.com/stolostron/search-indexer/pull/392 for eliminating the need to first parse request body to determine if request has ClearAll true or ClearAll false.
=> ACM-16129 add clear all bool to request header

.tekton/search-collector-acm-214-pull-request.yaml, .tekton/search-collector-acm-214-push.yaml, main.go, pkg/config/config.go, pkg/informer/runInformers_test.go, pkg/reconciler/reconciler_test.go, pkg/send/httpsClient_test.go, pkg/transforms/common_test.go
N/A
- Konflux updates were accidentally merged to release-2.14, so need to merge back to main.
=> Sync konflux updates merged to release-2.14 with main

.tekton/search-collector-acm-214-push.yaml
=> Fix konflux on-push config

.tekton/search-collector-acm-211-push.yaml
https://issues.redhat.com/browse/ACM-0000
- Added ...
=> [release-2.11] Fix konflux on-push config

.tekton/search-collector-acm-210-push.yaml
https://issues.redhat.com/browse/ACM-0000
- Added ...
=> [release-2.10] Fix konflux on-push config

Makefile, Makefile.prow, pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_test.go, pkg/transforms/common.go, pkg/transforms/genericresource.go, pkg/transforms/helmrelease.go, pkg/transforms/policy.go, pkg/transforms/policy_test.go, pkg/transforms/transformer.go, pkg/transforms/vapbinding.go, test-data/catalogsource.json, test-data/certpolicy.json, test-data/configurationpolicy.json, test-data/operatorpolicy.json, test-data/secret.json
These policy kinds report on related resources in their statuses.
Refs:
- https://issues.redhat.com/browse/ACM-20098
https://issues.redhat.com/browse/ACM-20098
- Added edges for Cert, Config, and Operator Policies
=> Add edges for Cert, Config, and Operator Policies

pkg/reconciler/reconciler_test.go, pkg/transforms/genericResourceConfig.go, pkg/transforms/genericResource_test.go, test-data/virtualmachinerestore.json
https://issues.redhat.com/browse/ACM-0000
- Collecting more properties for VirtualMachineSnapshot and VirtualMachineRestore resources.
=> Add generic transform for VirtualMachineRestore

README.md
N/A
- Rebuild image with UBI 9
=> [release-2.13] Rebuild image with UBI 9

README.md
=> [release-2.12] Rebuild image with UBI9

go.mod, go.sum
release notes with rename ref https://github.com/darccio/mergo/releases/tag/v1.0.0
=> replace imdario/mergo with new path dario.cat/mergo

.github/renovate.json
=> Reduce go package update PRs

pkg/reconciler/reconciler_test.go, pkg/transforms/genericResourceConfig.go, pkg/transforms/genericResource_test.go, pkg/transforms/persistentvolumeclaim.go, pkg/transforms/persistentvolumeclaim_test.go, pkg/transforms/transformer.go, test-data/persistentvolumeclaim.json, test-data/virtualmachine.json, test-data/virtualmachineinstance.json, test-data/virtualmachineinstancemigration.json
https://issues.redhat.com/browse/ACM-22579
- Added indexing of:
pvc: requestedStorage, volumeMode
vm: description, specRunStrategy
vmi: cpu, memory
vmim: statusPhase, endTimestamp
=> ACM-22579 easily indexed values of vm, vmi, vmim, pvc

.tekton/search-collector-acm-215-pull-request.yaml, .tekton/search-collector-acm-215-push.yaml
N/A
- Fixes konflux enterprise contract errors
=> Fix konflux enterprise contract errors

.tekton/search-collector-acm-215-push.yaml
- Added the other build platforms back
=> [main] re-enable multi-arch builds

.tekton/search-collector-acm-211-pull-request.yaml, .tekton/search-collector-acm-211-push.yaml, Dockerfile, Dockerfile.rhtap
- Added multi arch and hermetic builds
=> [release-2.11] multi arch hermetic builds

.ci-operator.yaml, Dockerfile, Dockerfile.rhtap, go.mod
- cherry-pick of https://github.com/stolostron/search-collector/pull/786
=> [release-2.10] update go to 1.24 (#786)

.ci-operator.yaml, Dockerfile, Dockerfile.rhtap, go.mod
- manual cherry-pick of https://github.com/stolostron/search-collector/pull/786
=> [release-2.11] update go to 1.24 (#786)
