- .travis.yml
**Related Issue:**  N/A
- Fixes release-ff - after making the repo public we can't use the ssh key anymore.
> Fix release-ff

- Makefile.prow
**Related Issue:**  open-cluster-management/backlog#9582
- Add unit-test target to Makefile.prow
> Prepare for prow - add unit-tests to Makefile.prow

- go.mod
- go.sum
**Related Issue:**  open-cluster-management/backlog#9611
Update version to 0.3.5
> update golang.org/x/text version

- go.mod
- go.sum
**Related Issue:**  open-cluster-management/backlog#9611
Update version to 0.3.5
> [release 2.2] update golang.org/x/text version

- pkg/reconciler/reconciler_test.go
- pkg/transforms/common.go
- pkg/transforms/common_test.go
- pkg/transforms/genericresource.go
**Related Issue:**  open-cluster-management/backlog#10696
- Removes selfLink.  It was removed in K8s 1.20
> remove deprecated selfLink

- pkg/transforms/policyreport.go
- pkg/transforms/policyreport_test.go
- test-data/policyreport.json
- Adding results field ("error" or "skip") to redis for PolicyReports
> Add policy report result field to redis

- pkg/transforms/argoapplication.go
- pkg/transforms/argoapplication_test.go
- test-data/argoapplication.json
**Related Issue:**  https://github.com/open-cluster-management/backlog/issues/11353
- Added the Argo app status to the search collector
The search query now return the status of the Argo app:
> Add Argo app status to search collector

- pkg/transforms/policyreport.go
- pkg/transforms/policyreport_test.go
- test-data/policyreport.json
https://github.com/open-cluster-management/backlog/issues/12669
- index the cluster scope of policyreport resources
> Add cluster scope of policyreport resources

- pkg/transforms/argoapplication.go
Signed-off-by: Feng Xiang <fxiang@redhat.com>
**Related Issue:**  https://github.com/open-cluster-management/backlog/issues/13638
- Check if targetRevision is empty and default to `HEAD`
> Default Argo targetRevision to HEAD

- main.go
- pkg/config/kubeClient.go
- pkg/lease/lease.go
**Related Issue:**  open-cluster-management/backlog#13558
Create lease on remote cluster namespace on HUB if lease object is not available on the managed cluster (OCP 311)
> Handle when managed cluster does not support lease kind

- main.go
- pkg/config/config.go
- pkg/config/kubeClient.go
- pkg/lease/lease.go
- pkg/lease/lease_test.go
- pkg/send/sender.go
**Related Issue:**  open-cluster-management/backlog#17342
open-cluster-management/backlog#17789
- Update the lease code to use the most current hub kube client every time the lease is renewed.
- Reload config after any lease errors.
- Reload config after any send error.
> Use the most current kube client connection for lease

- pkg/transforms/policyreport.go
- test-data/policyreport.json
**Related Issue:** open-cluster-management/backlog#19172
- Policy violation details are displayed elsewhere in the UI, displaying them in the PR will result in double counts on pages. So this PR filters the grc sourced violations from the PolicyReport node data.
> Filter out grc sourced vioilations from PolicyReport results

- build/run-lint-check.sh
**Related Issue:**  stolostron/backlog#<ISSUE_NUMBER>
Show lint errors clearly instead of 0/1 evaluation
> update lint script

- pkg/transforms/argoapplication.go
- test-data/argoapplication.json
Signed-off-by: Xiangjing Li <xiangli@redhat.com>
We found that one argo application status could be like this
- its health status is not healthy 
- its sync status is  not synced
- while its operationState phase is succeeded 
In this case, we should not bundle the operationState message as it is not error message
> don't bundle operationState message if its phase is succeeded

- Makefile
- main.go
- pkg/informer/informer.go
- pkg/informer/runInformers.go
N/A
- Refactor to simplify main by moving logic to start informers to a separate file.
- Better implementation comments.
> Refactor: simplify main by moving logic to start informers

- pkg/send/sender.go
https://issues.redhat.com/browse/ACM-5404
- Fixes bug in backoff logic, which caused REPOT_RATE_MS to not get honored after a successful send.
> ACM-5404: Fixes min wait after successful send

- pkg/informer/runInformers.go
- pkg/informer/runInformers_test.go
- pkg/informer/supportedResources.go
- pkg/send/sender.go
https://issues.redhat.com/browse/ACM-5402
- The loop to poll CRDs and start the informers was blocked on `initialized <- struct{}{}`
- Refactored the code to write to the initialized channel only once.
- Minor log adjustments.
> ACM-5402: Fixes problem when synchronizing informers

- Makefile
- Makefile.prow
- pkg/send/sender.go
https://issues.redhat.com/browse/ACM-5188
- Disable gosec rule G307.  This rule has been retired from gosec. [More info here.](https://github.com/securego/gosec/pull/935)
- Update makefile to run gosec with lint.
> ACM-5188 Sonar security finding

- pkg/config/config.go
- pkg/send/sender.go
- pkg/send/sender_test.go
- sonar-project.properties
N/A
- Adds random jitter to the backoff logic to prevent collectors form getting in the same retry cycle.
> Add jitter to backoff logic

- pkg/send/sender.go
- pkg/transforms/transformer.go
https://issues.redhat.com/browse/ACM-0000
- Remove the metadata field from JSON payload sent to indexer. This is only used by the collector.
- JSON payload size is reduced by about 8%.
- When sending 4886 resources, the payload size was reduced by 211472 bytes (2742099 - 2530627).
> Remove metadata from JSON payload

- pkg/transforms/node.go
- pkg/transforms/node_test.go
https://github.com/stolostron/backlog/issues/27387
- The Node `status` must be a single string instead of a list.
- Using list breaks the query for Pod status.
> Node status field must be a single string

- pkg/transforms/argoapplication.go
https://issues.redhat.com/browse/ACM-9746
- The logic to build edges for ArgoApps was logging excessively when resources aren't found for an app. We have logic to handle this scenario where resources aren't found, but the large volume of warning log messages causes problems.
> ACM-9746: Reduce excessive logging from Argo apps with missing resources

- go.mod
- pkg/reconciler/reconciler_test.go
- pkg/transforms/policy.go
- pkg/transforms/policy_test.go
- pkg/transforms/transformer.go
- test-data/certpolicy.json
- test-data/configurationpolicy.json
- test-data/operatorpolicy.json
Ref: 
Signed-off-by: yiraeChristineKim <yikim@redhat.com>
https://issues.redhat.com/browse/ACM-13031
Add properties such as responseAction, compliant, annotations, severity, parentPolicyName, and parentPolicyNs to config/operator/cert policy. 
Common properties:
- managedFields
- annotations
- compliant
- responseAction (Cert won't have this pe)
- severity
- parentPolicyName/parentPolicyNs
OperatorPolicy
- upgradeAvailable
- deploymentAvailable
> Add config/operator/cert policy transform

- pkg/transforms/common.go
- pkg/transforms/policy_test.go
The previous solution worked for unstructured and default types but not for the Policy kind. This new type works for all.
> Use a more generic type for detecting the API group

- config.json
- main.go
- pkg/config/config.go
- pkg/informer/informer.go
- pkg/informer/informer_test.go
- pkg/informer/runInformers.go
- pkg/informer/runInformers_test.go
- pkg/send/sender.go
- pkg/transforms/genericResourceConfig.go
- pkg/transforms/genericresource.go
- pkg/transforms/policy.go
- pkg/transforms/transformer.go
- pkg/transforms/transformer_test.go
The first commit is a slight performance enhancement in the generic informer. It's unrelated to the larger change but I figured I'd include it.
Gatekeeper constraints are CRD based but the CRDs are generated based on
user defined ConstraintTemplate objects. Because of this, indexing the
constraint's `spec.enforcementAction` and `status.totalViolations` is a
bit difficult with the current setup. This makes it so that the CRD's
additionalPrinterColumns are automatically indexed.
The scope of this change is limited to the constraints.gatekeeper.sh API
group, but removing that check in the the `GenericResourceBuilder`
function will enable it for all resources that don't have a custom
transform.
Note that the names from the additionalPrinterColumns in the CRD are
converted to lowerCamelCase …
> Index additional printer columns for Gatekeeper constraints 

- pkg/informer/runInformers.go
- pkg/informer/runInformers_test.go
There was a race condition of if the syncInformers function ran before a new CRD was established, an informer for the CRD didn't get created.
> Wait for the CRD to be ready before syncing informers

- pkg/transforms/genericResourceConfig.go
- pkg/transforms/genericResource_test.go
https://issues.redhat.com/browse/ACM-14658
- Collect desired state of Virtual Machine. (spec.running and spec.runStrategy)
- Using the names _specRunning and _specRunStrategy to indicate that this can change. Ideally we should combine these into a single field.
> ACM-14658 Collect desired state of VirtualMachine

- pkg/reconciler/reconciler_test.go
- pkg/transforms/kyverno.go
- pkg/transforms/kyverno_test.go
- pkg/transforms/policyreport.go
- pkg/transforms/policyreport_test.go
- pkg/transforms/testutils.go
- pkg/transforms/transformer.go
- test-data/kyverno-clusterpolicyreport.json
- test-data/kyverno-policyreport.json
PolicyReport indexing was previously focused on ACM policy results for Insights. This now also accounts for PolicyReport and ClusterPolicyReport objects generated by Kyverno by having the correct numRuleViolations values and edges created between the report and the Kyverno policy.
Note that the `policyViolationCounts` properties only rendered properly after this PR:
https://github.com/stolostron/search-v2-api/pull/261
Relates:
https://issues.redhat.com/browse/ACM-15127
> Index Kyverno policies and policy reports

- pkg/reconciler/reconciler_test.go
- pkg/transforms/common_test.go
- pkg/transforms/genericResourceConfig.go
- pkg/transforms/genericresource.go
- pkg/transforms/vapbinding.go
- pkg/transforms/vapbinding_test.go
- test-data/vap-gatekeeper-constraint.json
- test-data/vap-gatekeeper.json
- test-data/vap-selector.json
- test-data/vapb-gatekeeper.json
- test-data/vapb-selector.json
- test-data/vapbinding.json
A ValidationAdmissionPolicyBinding now has an edge to its ValidatingAdmissionPolicy. Additionally, all paramRefs are also added as edges to the ValidationAdmissionPolicyBinding.
Relates:
https://issues.redhat.com/browse/ACM-15249
> Add edges for VAP and VAPB

- pkg/transforms/vapbinding.go
- pkg/transforms/vapbinding_test.go
Add ownbyKyverno field in validatingadmissionpolicybinding
https://issues.redhat.com/browse/ACM-15318
- Add ownbyKyverno field in validatingAdmissionPolicyBinding
> Add ownbyKyverno field in validatingAdmissionPolicyBinding

- .gitignore
- pkg/transforms/common.go
- Add annotations to gatekeeper muation for severity to show on discovered policies
Signed-off-by: yiraeChristineKim <yikim@redhat.com>
https://issues.redhat.com/browse/ACM-16117 (bug)
- Add annotations to gatekeeper muation for severity to show on discovered policies
> Add annotations to gatekeeper muation for severity

- .tekton/search-collector-acm-213-pull-request.yaml
- renovate.json
N/A
- Updates the konflux schedule to run every Tuesday. Current cron expression isn't working as expected.
- Don't run konflux job on PRs to main.
> Update konflux schedule and don't run on PRs to main

- pkg/reconciler/reconciler.go
https://issues.redhat.com/browse/ACM-17312
- Skip rebuild edges when nothing has changed
- CPU usage reduced by ~60% 
- In the sample below cpu was reduced from a peak of 25m to 10m
- Slight memory reduction. The samples below show a larger gain, but it's not consistent.
> ACM-17312 Reduce CPU by skipping edge rebuild when nothing has changed

- pkg/informer/informer.go
- pkg/informer/informer_test.go
- Using builtin min func [introduced in Go 1.21](https://go.dev/blog/go1.21rc) since we bumped Go version.
> use builtin min func

- pkg/transforms/common.go
- pkg/transforms/common_test.go
- pkg/transforms/genericResourceConfig.go
- pkg/transforms/genericResource_test.go
- pkg/transforms/genericresource.go
- pkg/transforms/node.go
- pkg/transforms/node_test.go
- pkg/transforms/transformer.go
https://issues.redhat.com/browse/ACM-16461
- Added more resources to index for kind:Node
- Refactored GenericResourceBuilder to further generalize resource transforming. Permits adding more fields to defaultTransformConfig for resources that have a specific transforms file.
> ACM-16461 index more resources for kind node

- .tekton/search-collector-acm-214-pull-request.yaml
- Added fix for failure: https://github.com/stolostron/search-collector/pull/551/checks?check_run_id=40876484755 according to https://github.com/konflux-ci/build-definitions/blob/main/task/sast-snyk-check/0.4/MIGRATION.md
> add image-digest value for sast-coverity-check-oci-ta

- .tekton/search-collector-acm-211-pull-request.yaml
- moved image-digest and image-url params according to https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1745404637499059?thread_ts=1745339419.829389&cid=C04PZ7H0VA8
> [release-2.11] fix sast-snyk-check params

- .tekton/search-collector-acm-210-pull-request.yaml
- moved image-digest and image-url params according to https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1745404637499059?thread_ts=1745339419.829389&cid=C04PZ7H0VA8
> [release-2.10] fix sast-snyk-check params

- pkg/transforms/common.go
- pkg/transforms/transformer_test.go
It had been returning too early after not finding the transform config - and the unit test was not actually checking for these properties.
Refs:
- https://issues.redhat.com/browse/ACM-20932
https://issues.redhat.com/browse/ACM-20932
- Fix collection of gatekeeper constraint properties
> Fix collection of gatekeeper constraint properties

- pkg/reconciler/reconciler_test.go
- pkg/transforms/policy.go
Previously, related items on policies would only be put into the noncompliant list if they existed. However, many (not all) missing resources should also be considered as noncompliant.
Refs:
- https://issues.redhat.com/browse/ACM-20098
https://issues.redhat.com/browse/ACM-20098
- Always mark noncompliant related resources of policies.
> Always mark noncompliant policy resources

- README.md
- go.mod
- go.sum
- main.go
- pkg/config/config.go
- pkg/config/kubeClient.go
- pkg/informer/informer.go
- pkg/informer/runInformers.go
- pkg/informer/supportedResources.go
- pkg/lease/lease.go
- pkg/reconciler/reconciler.go
- pkg/reconciler/reconciler_test.go
- pkg/send/httpsClient.go
- pkg/send/sender.go
- pkg/transforms/argoapplication.go
- pkg/transforms/common.go
- pkg/transforms/helmrelease.go
- pkg/transforms/pod.go
- pkg/transforms/policy.go
- pkg/transforms/transformer.go
- pkg/transforms/vapbinding.go
N/A
- The project now consistently uses klog/v2 for logging instead of the older glog library, which aligns with Kubernetes ecosystem best practices. All logging functionality should work exactly the same, as klog provides the same API as glog but with additional features and better integration with the Kubernetes ecosystem
> Replace glog with klog

- pkg/config/config.go
- pkg/reconciler/reconciler_test.go
- pkg/transforms/common.go
- pkg/transforms/genericResourceConfig.go
- pkg/transforms/genericResource_test.go
- pkg/transforms/node_test.go
- pkg/transforms/pod.go
- pkg/transforms/pod_test.go
- pkg/transforms/transformer.go
https://issues.redhat.com/browse/ACM-22579
https://issues.redhat.com/browse/ACM-2071
- Added ability to index status conditions as map[string]string just like labels. Added config to enable for all resource kinds, defaults to false and will gather conditions on VMs, Nodes, Pods, Search, and MCH by default while we test the functionality before eventually enabling for all resources.
> ACM-22579 collect status conditions

- pkg/transforms/common.go
- pkg/transforms/genericResourceConfig.go
- pkg/transforms/genericResource_test.go
- pkg/transforms/transformer.go
- test-data/virtualmachine.json
https://issues.redhat.com/browse/ACM-22579
- Added relationships VM --_attachedTo_--> PVC,
- VM --_attachedTo_--> DV,
- VMIM --_migrationOf_--> VMI
Special logic had to be introduced to handle JSONPATH extracting nested slices, this should be eventually generalized with the configurable search collection
> ACM-22579 index pvc claim names and data volume names on vm, vmi on vmim
